### ISSUE TITLE
when I selete some text , I can not read it clearly

### ISSUE THREAD

**Issue by wduin** [elitistsnob/typora-cobalt-theme#5]
just like this picture

![Xnip2020-05-03_13-13-28](https://user-images.githubusercontent.com/50404173/80899198-f6b90c80-8d3f-11ea-8769-35622596ea27.jpg)

And , when I use shift+command+O to open some file ,it  occured this too，just like this picture .
![image](https://user-images.githubusercontent.com/50404173/80899254-b5752c80-8d40-11ea-9301-c376f6ac5fbe.png)

thanks.

**Comment by pulkitnt** [comment]
any news on this issue? it really is a pain!

**Comment by richc117** [comment]
@pulkitnt @elitistsnob @XavierZfc 
Agreed this is painful! Looks like the standard [Night Theme](https://github.com/typora/typora-default-themes/tree/master/themes/night) seems to have this resolved.

**Comment by elitistsnob** [comment]
Guys, this is already resolved. You need to download the latest release here and copy over your local theme files. 

https://github.com/elitistsnob/typora-cobalt-theme/releases/tag/v1.4

**Comment by richc117** [comment]
ahh man I went in and fixed the issue was going to post here but glad its already fixed thank @elitistsnob

**Comment by richc117** [comment]
@elitistsnob I downloaded the latest version from the link you posted and I was still having the same issue. When I select text using the cursor. For example when I am copying text so I paste anywhere else, the selected text is no longer legible because the background clashes with the foreground text. 

I was able to fix the issue by adding this to the top of [cobalt.css](https://github.com/elitistsnob/typora-cobalt-theme/blob/master/cobalt.css) file:

```css
    --primary-color-rgb: rgba(239, 183, 82) ;
    --text-highlight-color: #fff;
    --text-highlight-bg: rgba(var(--primary-color-rgb), 0.3);
    --select-text-bg-color: rgba(255, 255, 255, 0.2);
    --search-select-text-color: var(--text-highlight-color);
    --search-select-bg-color: var(--text-highlight-bg);
```
